[package]
name = "jvm"
version = "0.1.0"
authors = ["douchuan <douchuan@aixlu.com>"]
edition = "2018"

[dependencies]
bytes = "0.4.12"
chrono = "0.4.9"
env_logger = "0.6.1"
lazy_static = "1.4.0"
log = "0.4.0"
nix = "0.15.0"
zip = "0.5.3"
